### ISSUE TITLE
Make a bar above the normal stats bar that show regoinal statisitcs

### ISSUE THREAD

**Issue by Adiack06** [Jachdich/economy-program#15]
Population 
Jobs 
GDP?
Employment rate

**Comment by Jachdich** [comment]
How should I do GDP? Since commuting is a thing, a town with more houses than jobs can make a lot more money than it would seem by analysing it alone, same with a region with more jobs than houses. I could do the income of the industry in that region, like I did in the pie chart, but it isn't an accurate picture of GDP. In fact I am considering removing that from the pie chart cos it isn't really that useful.

**Comment by Adiack06** [comment]
income by region is very important do it by how much the indsutrty in the region earns
